### ISSUE TITLE
Not able to compile the examples

### ISSUE THREAD

**Issue by mathstudi** [microchip-pic-avr-examples/avr128da48-cnano-manchester-mplab-mcc#2]
I use:
- MPLAB X IDE v6.20
- MPLAB XC8 v2.46
- AVR-Dx_DFP v2.4.286

After "Clean and Build":
In file included from mcc_generated_files/uart/src/../../system/system.h:43:0,
                 from mcc_generated_files/uart/src/../usart1.h:43,
                 from mcc_generated_files/uart/src/usart1.c:38:
mcc_generated_files/uart/src/../../system/../system/utils/compiler.h:64:28: fatal error: interrupt_avr8.h: No such file or directory
compilation terminated.
make[2]: *** [nbproject/Makefile-free.mk:204: build/free/production/mcc_generated_files/uart/src/usart1.o] Error 1

The interrupt_avr8.h is already in the utils directory.

**Comment by mathstudi** [comment]
Problem solved. The directory length was too long.

**Comment by pic-avr-github-admin** [comment]
Closing issue as it was self-resolved. Please reach out again if you encounter any issues in the future.
